name: Ubuntu CI

on:
  push:
    branches:
      - main
      - dev
    tags:
      - v*

env:
  BUILD_TYPE: Release
  GNU_CC: gcc-9
  GNU_CXX: g++-9
  LLVM_CC: clang-11
  LLVM_CXX: clang++-11

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install GNU C/C++ Compiler
        if: ${{ matrix.compiler == 'gcc' }}
        run: |
          export GNU_CC=gcc
          export GNU_CXX=g++

      - name: Install LLVM Clang
        if: ${{ matrix.compiler == 'clang' }}
        run: |
          export LLVM_CC=clang
          export LLVM_CXX=clang++

      - name: Install OpenCV
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libopencv-dev

      - name: CMake Build
        run: |
          cmake . -B ${{runner.workspace}}/build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -G Ninja 
          cmake --build ${{runner.workspace}}/build --config $BUILD_TYPE --parallel 2
