name: Ubuntu CI

on:
  push:
    branches:
      - main
      - dev
    tags:
      - v*

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: clang
          - os: macos-latest
            compiler: clang
          - os: macos-latest
            compiler: gcc
          - os: windows-latest
            compiler: msvc

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install GNU C/C++ Compiler
        if: ${{ matrix.compiler == 'gcc' }}
        run: |
          export GNU_CC=gcc
          export GNU_CXX=g++

      - name: Install LLVM Clang
        if: ${{ matrix.compiler == 'clang' }}
        run: |
          export LLVM_CC=clang
          export LLVM_CXX=clang++

      - name: Install OpenCV
        run: |
          git clone --depth 1 https://github.com/opencv/opencv.git --branch 4.12.0
          cd opencv
          cmake . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/opencv_install
          cmake --build build --target install --config Release --parallel 2

      - name: CMake Build
        run: |
          cmake . \
            -G Ninja \
            -B ${{runner.workspace}}/build \
            -DCMAKE_BUILD_TYPE=Release
            -DOpenCV_DIR=${{runner.workspace}}/opencv_install/lib/cmake/opencv4 \
          cmake \
            --build ${{runner.workspace}}/build \
            --config Release \
            --parallel 2
